bind = $mainMod SHIFT, R, exec, ~/.config/rofi/edit_dotfiles.sh # Edit Dotfiles
bind = $mainMod, slash, exec, ~/.config/rofi/show_keybinds.sh # Show Keybindings
bind = $mainMod, PRINT, exec, hyprshot -m region # Screenshot

